version = 1

test_patterns = ["**/*_test.go"]

exclude_patterns = ["**/*.pb.go"]

[[analyzers]]
name = "secrets"

[[analyzers]]
name = "go"

  [analyzers.meta]
  import_root = "github.com/wwi21seb-projekt/alpha-shared"